name: Bump casks on schedule or request

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: read

jobs:
  autobump:
    runs-on: macos-latest
    steps:
      - name: Generate Bot Token
        id: generate-token
        uses: actions/create-github-app-token@v3.1.1
        with:
          app-id: ${{ secrets.FLADDER_BOT_APP_ID }}
          private-key: ${{ secrets.FLADDER_BOT_APP_PRIVATE_KEY }}

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          core: false
          cask: true
          token: ${{ steps.generate-token.outputs.token }}

      - name: Configure Git user
        run: |
          git config --global user.name "fladder-bot[bot]"
          git config --global user.email "fladder-bot[bot]@users.noreply.github.com"

      - name: Bump casks
        uses: Homebrew/actions/bump-packages@main
        continue-on-error: true
        with:
          token: ${{ steps.generate-token.outputs.token }}
          casks: "fladder"
          fork: false
        env:
          HOMEBREW_TEST_BOT_AUTOBUMP: 1
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
